server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:/data/db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect