server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:osbb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql

web:
  monobank:
    url: https://api.monobank.ua/bank/currency

jwt:
  secret: secret